### ISSUE TITLE
api: Show events

### ISSUE THREAD

**Issue by aefhm** [oasisprotocol/nexus#208]
##### SUMMARY

Let's present the events from #188 

Introduce 2 new API endpoints:

/v1/consensus/blocks/{height}/events
/v1/consensus/transactions/{hash}/events

This should return all events associated.

##### ISSUE TYPE
- Feature Idea

**Comment by mitjat** [comment]
Presumably this will take the form of an `events` property on the [`Block`](https://github.com/oasisprotocol/oasis-indexer/blob/305095e8b1c04916924b517eeca4405d97586a90/api/spec/v1.yaml#L846-L846) and [`Transaction`](https://github.com/oasisprotocol/oasis-indexer/blob/305095e8b1c04916924b517eeca4405d97586a90/api/spec/v1.yaml#L938-L938)?

**Comment by aefhm** [comment]
> Presumably this will take the form of an events property on the [Block](https://github.com/oasisprotocol/oasis-indexer/blob/305095e8b1c04916924b517eeca4405d97586a90/api/spec/v1.yaml#L846-L846) and [Transaction](https://github.com/oasisprotocol/oasis-indexer/blob/305095e8b1c04916924b517eeca4405d97586a90/api/spec/v1.yaml#L938-L938)?

Yeah, lemme beef up description 😅 .

I think the two use cases are show me all events in a `block`, and show me all events associated with a `transaction`.

**Comment by mitjat** [comment]
https://app.clickup.com/t/3t234wk

**Comment by Andrew7234** [comment]
#277 added support for events, including filtering by tx_hash and block. The remaining work in this ticket would be to add an  `events` property to `Transaction` and `Block`, and populate it with the Events Query. In the meantime, users can simply make an additional call to the `consensus/events` endpoint. 

Since 1) the functionality now exists and 2) we are prioritizing emerald, this ticket was downgraded to p3

**Comment by ptrus** [comment]
Using the events endpoints is sufficient. No need to duplicate this across multiple endpoints.
