### ISSUE TITLE
analyzer/api: Improve e2e testing

### ISSUE THREAD

**Issue by aefhm** [oasisprotocol/nexus#77]
##### SUMMARY

Add e2e tests for the staking/commission/validator endpoints.

##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION

@mitjat wrote:

> 2e regression tests are a higher priority right now, e.g. [e2e regression test: Support non-block analyzers](https://github.com/oasisprotocol/nexus/pull/519) ; they give us most of the bang for a lot less buck.

> But for corner cases, synthetic e2e tests would still be useful. Example of a recent bug that we cannot easily verify via regression tests because it occurs so rarely: https://github.com/oasisprotocol/nexus/pull/517

**Comment by mitjat** [comment]
The infra for e2e testing is now built in #142 , but these tests need to be written still.

**Comment by mitjat** [comment]
https://app.clickup.com/t/3r2m45u

**Comment by pro-wh** [comment]
Comment from Mitja Trampus

e2e regression tests are a higher priority right now, e.g. [e2e regression test: Support non-block analyzers](https://app.clickup.com/t/866aak668) ; they give us most of the bang for a lot less buck.


But for corner cases, synthetic e2e tests would still be useful. Example of a recent bug that we cannot easily verify via regression tests because it occurs so rarely: https://github.com/oasisprotocol/nexus/pull/517

**Comment by ptrus** [comment]
This has been implemented in https://github.com/oasisprotocol/nexus/pull/627
