### ISSUE TITLE
Add query param to enable/disable sorting by market cap

### ISSUE THREAD

**Issue by buberdds** [oasisprotocol/nexus#815]
API endpoint:
https://nexus.prd.oasis.io/v1/sapphire/evm_tokens?limit=10&offset=0

During LJU Summit there was discussion around changing how we sort token list  by market cap. Until these changes are implemented can we just simply turn off sorting by market cap for time being? Whether it is hardcoded or query param is provided it's up to backend.

context: showing some "Sapphire" token as the first one might be misleading for novice users.

As this is extra work let's wait for @tjanez input first. 

- Current production (stg instance):
![Screenshot from 2024-12-02 13-45-30](https://github.com/user-attachments/assets/b5def919-d66c-4156-b8eb-10507d018358)

- Token list after the update (prd instance)
![Screenshot from 2024-12-02 13-45-24](https://github.com/user-attachments/assets/368d536f-148f-42c4-822d-69057e779275)

**Comment by tjanez** [comment]
I'm in favor of temporarily disabling sorting by market cap (regardless of how it is implemented) because of the following:
1. As in the example screenshots above, the current market cap metric can be manipulated quite easily and if we would release this as is, some scam "Sapphire" token would be elevated to the top spot.
2. The current implementation of obtaining relative token prices relies on illumineX decetralized exchange (DEX), however, the illumineX team is shifting its focus away from providing a DEX to other private wallet solutions. The Neby DEX was just launched and it will probably make sense to port the token analyser code to use Neby's APIs instead of illumineX's APIs.

**Comment by kostko** [comment]
Sorting by market cap only makes sense if it also takes price into account. Otherwise this can be easily manipulated.

**Comment by ptrus** [comment]
I think It does? but I believe the problem is that due to the small markets it can still be manipulated.

**Comment by kostko** [comment]
Ah you're right, even that doesn't help.
