### ISSUE TITLE
API evm_tokens call sometimes times out

### ISSUE THREAD

**Issue by buberdds** [oasisprotocol/nexus#816]
Provided by Gregor
```
024/12/03 11:47:47 http: superfluous response.WriteHeader call from github.com/oasisprotocol/nexus/api.HumanReadableJsonErrorHandler (errors.go:72)
```

**Comment by ptrus** [comment]
It seems like evm_tokens request is timing out from time to time.

To reproduce run `curl "https://nexus.prd.oasis.io/v1/sapphire/evm_tokens?limit=10&offset=0"` a few times.

Relevnat logs:
```json
{"caller":"middleware.go:62","endpoint":"/v1/sapphire/evm_tokens","level":"info","module":"api","msg":"starting request","request_id":"dae27863-bf66-49aa-bcd1-bc71ad6f13fc","ts":"2024-12-05T14:12:08.15331038Z"}
2024/12/05 14:12:21 http: superfluous response.WriteHeader call from github.com/oasisprotocol/nexus/api.HumanReadableJsonErrorHandler (errors.go:72)
{"caller":"middleware.go:77","latency":"13.17662808s","latency_bin":">1000ms","level":"info","module":"api","msg":"ending request","query_params":"limit=100&offset=10","query_path":"/v1/sapphire/evm_tokens","request_id":"dae27863-bf66-49aa-bcd1-bc71ad6f13fc","status_code":200,"ts":"2024-12-05T14:12:21.330041411Z"}
```

This might be connected to  https://github.com/oasisprotocol/nexus/pull/691 or https://github.com/oasisprotocol/nexus/pull/755 since this doesn't happen in the pre-index deployments (also doesn't happen on "testnet.nexus.prd.oasis.io", where we don't calculate these prices).

Can @Andrew7234  or @pro-wh  please take a look? I have a lot of other things at the moment and I am also not super familiar with these changes.

There is also an open issue to support the sorting by market-cap only optionally (via request param): https://github.com/oasisprotocol/nexus/issues/815

**Comment by pro-wh** [comment]
our API code doesn't call WriteHeader by itself, it must be in whatever scaffolding we use

**Comment by ptrus** [comment]
I checked this a bit, and It looks like the `ix_evm_token_address` index scan and then aggregating the holders seems to be the slowest (https://github.com/oasisprotocol/nexus/blob/fceee2c98cc108aa7c2da68714d5b8ad51e6485f/storage/client/queries/queries.go#L649-L654). The index looks fine for the query, but it looks like that the DB is resource constrained (CPU utilization is 90%+ constantly). Will try to get the DB cpu's bumped, and this might get better. There is also high variability in the query latency times.

**Comment by ptrus** [comment]
This works better now that the DB was updated to have more CPUs available.
