### ISSUE TITLE
api: Get all activity related to an account

### ISSUE THREAD

**Issue by aefhm** [oasisprotocol/nexus#88]
Independent endpoints for each ParaTime /consensus

1. Start with transactions related to an account
2. Later extend with events related to an account

**Comment by aefhm** [comment]
We would need events as well.

Staking rewards progression would be nice.

**Comment by mitjat** [comment]
https://app.clickup.com/t/3t22md6

**Comment by mitjat** [comment]
I would argue that largely, activity == events. This will include things not covered by txs, like end of debonding, or the payout of staking rewards at the end of an epoch.
Well, we'll also want to show failed txs, I guess? But events are the main star. 

#246 is the first step towards adding events; it covers just the openAPI. The remaining work is (copied from #246 description for visibility):
- "Just" piping through what we already have in the DB. Most of the fields fall in this category. Still quite a bit of work because of all of our boilerplate.
- Implementing the "related addresses" field for events will require a new DB table (columns `event_id`, `related_address`; the former is a FK into `events`, which still needs a synthetic, internal-only PK id) and an extension to [this large nested `switch` statement](https://github.com/oasisprotocol/oasis-indexer/blob/d48de379c258fc467e09f33ecd614c03bfb8847d/analyzer/consensus/consensus.go#L840-L840) in the analyzer so that we'll extract whatever addresses are involved in the event, regardless of the type.

**Comment by pro-wh** [comment]
events related addresses might be nice to have. currently we have separate tables for different kinds of events, each with dedicated columns, so maybe we could get by with a great big union. although I think we currently lose the ordering due to events being in different tables

farther out idea: display non-transaction events among transactions. as a special non-transaction transaction/transactions per block. we do this in the rosetta gateway. and we'll possibly treating the consensus chain as the non-paratime paratime :face_with_spiral_eyes: speaking from the explorer perspective, where a lot of existing explorers are focused on events. imo this does a better job of meeting users where they are :shrug:

**Comment by Andrew7234** [comment]
I like the idea of having a `related_events` table in addition to the `related_transactions` table Mitja described. It should make the events query simpler(=faster), and it also nicely handles events that don't have a corresponding transaction. 

> switch-analyze the tx itself to find any associated addresses
I know we can extract the `sender` from the tx signature public key; are there any other addresses that can be extracted besides the ones from the tx.Results.Events?

**Comment by csillag** [comment]
Copying discussion from elsewhere:

@Andrew7234:

> Closed by https://github.com/oasisprotocol/oasis-indexer/pull/277/

**Comment by ptrus** [comment]
This was implemented.
